services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/kotlinconfg
      - DATABASE_MAX_CONNECTIONS=5
      - APP__SERVER__HOST=0.0.0.0
      - APP__SERVER__PORT=8080
      - APP__SERVICE__ENVIRONMENT=production
      - APP__SERVICE__SECRET=admin
      - RUST_LOG=info
      - SQLX_OFFLINE=true
      - DOCKER_ENV=1
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=kotlinconfg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  importService:
    image: criticalstrike/bulk-export-import:latest
    ports:
      - "8000:8000"
    environment:
      - STORAGE_DIR=/app/storage
      - PORT=8000
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DBNAME=kotlinconfg
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - BACKEND_URL=http://backend:8080
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge